require 'io/console'
require 'activate_my_directory'
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
#

class Get
  class << self
    def credentials
      [username, password]
    end

    def username
      return @username if @username
      print "\n"
      puts "Please enter your ActiveDirectory credentials"
      print "username: "
      @username = gets.chomp
    end

    def password
      username
      return @password if @password
      print "password: "
      @password = STDIN.noecho(&:gets).chomp
      print "\n"
      @password
    end
  end
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
